### ISSUE TITLE
previous_tag not populated

### ISSUE THREAD

**Issue by Zageron** [craig-day/compute-tag#1]
I'm attempting to grab the previous tag from the repository, this is my understanding of how I would do that. I have a 'v1.1.1' tag about 10 commits back.

```yaml
- name: Get tag if branch push.
  if: github.event_name == 'push' && !contains(github.ref, 'tags')
  id: compute_tag
  uses: craig-day/compute-tag@v9
  with:
    github_token: ${{ github.token }}
    version_scheme: semantic
- name: Add old version number if branch push.
  if: github.event_name == 'push' && !contains(github.ref, 'tags')
  uses: cschleiden/replace-tokens@v1
  with:
    files: '["asconfig.release.json"]'
  env:
    VERSION: ${{ steps.compute_tag.outputs.previous_tag }}
```
