### ISSUE TITLE
Wrongly computed next tag for semantic patch

### ISSUE THREAD

**Issue by BrokenSwing** [craig-day/compute-tag#21]
Hello,
I tried to update our version of the action from v10 to v15 and got it fail because it doesn't correctly compute the next tag.

Here is the action call:
```yaml
- name: Compute next tag
  id: compute-tag
  uses: craig-day/compute-tag@v10
  with:
    github_token: ${{ github.token }}
    version_scheme: semantic
    version_type: "${{ fromJSON(steps.compute-release.outputs.release).type }}"
```

Here is my output of the action:
```
Run craig-day/compute-tag@v15
  with:
    github_token: ***
    version_scheme: semantic
    version_type: patch
    tag_fetch_depth: 10
    prerelease_suffix: beta
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.0/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.0/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.0/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.0/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.0/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.0/x64/lib:/usr/local/lib
Fetching tags.
Computing the next tag based on: v17.7.17
Computed the next tag as: v17.7.17
```

As we can see, the patch number of the tag didn't get bumped while we correctly provide the arguments for patch semantic.
